export const persons = [
  {
    id: 'leo',
    name: 'Leo',
    fullName: 'Leonardo Alloni',
    role: 'Frontend · Commerciale',
    emoji: '🎨',
    hex: '#3b82f6',
    threeColor: 0x3b82f6,
    deskColor: 0xdbeafe,
    screenColor: 0x0284c7,
    position: [-7, 0, -3],
    camPos: [-7, 2.2, 1.5],
    camTarget: [-7, 1.3, -3],
    bio: 'Il volto del progetto. Trasforma wireframe in interfacce bellissime e poi le vende al cliente con un sorriso.',
    funFact: 'Se gli chiedi un bottone veloce, ti consegna tre varianti, due hover e una vendita chiusa.',
    tags: ['React', 'CSS', 'Figma', 'Sales'],
    skills: [
      { name: 'Figma', level: 95 },
      { name: 'React', level: 88 },
      { name: 'CSS', level: 91 },
      { name: 'Sales', level: 83 },
    ],
    social: { github: '', linkedin: '', email: '' },
    deskType: 'designer',
  },
  {
    id: 'teo',
    name: 'Teo',
    fullName: 'Matteo Vattimo',
    role: 'Project Owner · Dev · IT',
    emoji: '📋',
    hex: '#f97316',
    threeColor: 0xf97316,
    deskColor: 0xffedd5,
    screenColor: 0xea580c,
    position: [-3, 0, 1.5],
    camPos: [-3, 2.2, 6],
    camTarget: [-3, 1.3, 1.5],
    bio: 'Il comandante silenzioso. Tiene tutto sotto controllo con milestone, sprint e una quantita industriale di caffe.',
    funFact: 'Non perde mai il filo: al massimo apre una board nuova per spiegare perche non l ha perso.',
    tags: ['Scrum', 'Jira', 'Network', 'Code'],
    skills: [
      { name: 'Scrum', level: 92 },
      { name: 'Jira', level: 87 },
      { name: 'Network', level: 74 },
      { name: 'Dev', level: 70 },
    ],
    social: { github: '', linkedin: '', email: '' },
    deskType: 'pm',
  },
  {
    id: 'napo',
    name: 'Napo',
    fullName: 'Filippo Napolitano',
    role: 'Ideatore · Dev · Dir. Amm.',
    emoji: '💡',
    hex: '#8b5cf6',
    threeColor: 0x8b5cf6,
    deskColor: 0xede9fe,
    screenColor: 0x7c3aed,
    position: [0, 0, -5],
    camPos: [0, 2.5, 0],
    camTarget: [0, 1.3, -5],
    bio: "La mente dietro tutto. Ogni lunedi ha l idea del secolo. Il venerdi e gia cambiata tre volte.",
    funFact: 'Le sue idee arrivano cosi in fretta che il team deve fare deploy solo per stargli dietro.',
    tags: ['Strategy', 'Vision', 'Admin', 'Dev'],
    skills: [
      { name: 'Strategy', level: 96 },
      { name: 'Vision', level: 93 },
      { name: 'Admin', level: 81 },
      { name: 'Dev', level: 67 },
    ],
    social: { github: '', linkedin: '', email: '' },
    deskType: 'director',
  },
  {
    id: 'andre',
    name: 'Andre',
    fullName: 'Andrea di Pietro',
    role: 'Tester · Supporto Tecnico',
    emoji: '🔍',
    hex: '#10b981',
    threeColor: 0x10b981,
    deskColor: 0xd1fae5,
    screenColor: 0x059669,
    position: [3, 0, 1.5],
    camPos: [3, 2.2, 6],
    camTarget: [3, 1.3, 1.5],
    bio: 'Il cacciatore di bug. Trova errori nel codice che non e ancora stato scritto.',
    funFact: 'Ha rotto 3 ambienti di staging solo guardandoli fissi.',
    tags: ['QA', 'Testing', 'Debug', 'Support'],
    skills: [
      { name: 'Testing', level: 94 },
      { name: 'QA', level: 91 },
      { name: 'Debug', level: 89 },
      { name: 'Support', level: 82 },
    ],
    social: { github: '', linkedin: '', email: '' },
    deskType: 'tester',
  },
  {
    id: 'dalla',
    name: 'Dalla',
    fullName: 'Matteo Dallavalle',
    role: 'Developer · DB Admin · Support',
    emoji: '🗄️',
    hex: '#06b6d4',
    threeColor: 0x06b6d4,
    deskColor: 0xcffafe,
    screenColor: 0x0891b2,
    position: [7, 0, -3],
    camPos: [7, 2.2, 1.5],
    camTarget: [7, 1.3, -3],
    bio: 'Il custode dei dati. Sa dove vive ogni record, anche quelli che non sai di avere.',
    funFact: 'I suoi JOIN sono cosi ottimizzati che il database gli manda i complimenti.',
    tags: ['SQL', 'PostgreSQL', 'Dev', 'Support'],
    skills: [
      { name: 'SQL', level: 96 },
      { name: 'PostgreSQL', level: 93 },
      { name: 'Dev', level: 79 },
      { name: 'Support', level: 77 },
    ],
    social: { github: '', linkedin: '', email: '' },
    deskType: 'db',
  },
]
