export const persons = [
  {
    id: 'leo',
    name: 'Leo',
    fullName: 'Leonardo Alloni',
    role: 'Frontend · Commerciale',
    emoji: '🎨',
    hex: '#3b82f6',
    threeColor: 0x3b82f6,
    deskColor: 0xdbeafe,
    screenColor: 0x0284c7,
    position: [-10.4, 0, -6],
    camPos: [-10.4, 1.6, -3.5],
    camTarget: [-10.4, 1.2, -6],
    doorway: [-10.4, 1.6, -2.5],
    bio: 'Quello che ti convince che il bottone è perfetto anche se lo ha spostato di 1px a sinistra per tre ore. Metà designer, metà venditore, metà crisi esistenziale su quale font usare.',
    funFact: 'Una volta ha litigato con un cliente per 40 minuti sul colore di un bordo che nessun utente avrebbe mai notato. Ha vinto lui.',
    tags: ['React', 'CSS', 'Figma', 'Sales'],
    deskType: 'designer',
  },
  {
    id: 'teo',
    name: 'Teo',
    fullName: 'Matteo Vattimo',
    role: 'Project Owner · Dev · IT',
    emoji: '📋',
    hex: '#f97316',
    threeColor: 0xf97316,
    deskColor: 0xffedd5,
    screenColor: 0xea580c,
    position: [-8, 0, 6],
    camPos: [-8, 1.6, 4.5],
    camTarget: [-8, 1.2, 6],
    doorway: [-8, 1.6, 2.5],
    bio: 'Il comandante silenzioso. Tiene tutto sotto controllo con milestone, sprint e una quantità industriale di caffè.',
    funFact: 'Ha uno sticky note per catalogare tutti i suoi sticky note.',
    tags: ['Scrum', 'Jira', 'Network', 'Code'],
    deskType: 'pm',
  },
  {
    id: 'napo',
    name: 'Napo',
    fullName: 'Filippo Napolitano',
    role: 'Ideatore · Dev · Dir. Amm.',
    emoji: '💡',
    hex: '#8b5cf6',
    threeColor: 0x8b5cf6,
    deskColor: 0xede9fe,
    screenColor: 0x7c3aed,
    position: [0, 0, -9],
    camPos: [0, 1.6, -6.5],
    camTarget: [0, 1.2, -9],
    doorway: [0, 1.6, -2.5],
    bio: "La mente dietro tutto. Ogni lunedì ha l'idea del secolo. Il venerdì è già cambiata tre volte.",
    funFact: 'Il suo whiteboard ha un whiteboard figlio per i dettagli.',
    tags: ['Strategy', 'Vision', 'Admin', 'Dev'],
    deskType: 'director',
  },
  {
    id: 'andre',
    name: 'Andre',
    fullName: 'Andrea di Pietro',
    role: 'Tester · Supporto Tecnico',
    emoji: '🔍',
    hex: '#10b981',
    threeColor: 0x10b981,
    deskColor: 0xd1fae5,
    screenColor: 0x059669,
    position: [8, 0, 6],
    camPos: [8, 1.6, 4.5],
    camTarget: [8, 1.2, 6],
    doorway: [8, 1.6, 2.5],
    bio: 'Il cacciatore di bug. Trova errori nel codice che non è ancora stato scritto.',
    funFact: 'Ha rotto 3 ambienti di staging solo guardandoli fissi.',
    tags: ['QA', 'Testing', 'Debug', 'Support'],
    deskType: 'tester',
  },
  {
    id: 'dalla',
    name: 'Dalla',
    fullName: 'Matteo Dallavalle',
    role: 'Developer · DB Admin · Support',
    emoji: '🗄️',
    hex: '#06b6d4',
    threeColor: 0x06b6d4,
    deskColor: 0xcffafe,
    screenColor: 0x0891b2,
    position: [10.4, 0, -6],
    camPos: [10.4, 1.6, -3.5],
    camTarget: [10.4, 1.2, -6],
    doorway: [10.4, 1.6, -2.5],
    bio: 'Il custode dei dati. Sa dove vive ogni record, anche quelli che non sai di avere.',
    funFact: 'I suoi JOIN sono così ottimizzati che il database gli manda i complimenti.',
    tags: ['SQL', 'PostgreSQL', 'Dev', 'Support'],
    deskType: 'db',
  },
]
