export const persons = [
  {
    id: 'leo',
    name: 'Leo',
    fullName: 'Leonardo Alloni',
    role: 'Frontend · Commerciale',
    emoji: '🎨',
    hex: '#3b82f6',
    threeColor: 0x3b82f6,
    deskColor: 0xdbeafe,
    screenColor: 0x0284c7,
    position: [-8, 0, -3],
    camPos: [-8, 2.5, 1.5],
    camTarget: [-8, 1.3, -3],
    bio: 'Il volto del progetto. Trasforma wireframe in interfacce bellissime e poi le vende al cliente con un sorriso.',
    funFact: 'Ha aperto Figma così tante volte che il logo è impresso nella sua retina.',
    tags: ['React', 'CSS', 'Figma', 'Sales'],
    deskType: 'designer',
  },
  {
    id: 'teo',
    name: 'Teo',
    fullName: 'Matteo Vattimo',
    role: 'Project Owner · Dev · IT',
    emoji: '📋',
    hex: '#f97316',
    threeColor: 0xf97316,
    deskColor: 0xffedd5,
    screenColor: 0xea580c,
    position: [-3, 0, 2],
    camPos: [-3, 2.5, 6.5],
    camTarget: [-3, 1.3, 2],
    bio: 'Il comandante silenzioso. Tiene tutto sotto controllo con milestone, sprint e una quantità industriale di caffè.',
    funFact: 'Ha uno sticky note per catalogare tutti i suoi sticky note.',
    tags: ['Scrum', 'Jira', 'Network', 'Code'],
    deskType: 'pm',
  },
  {
    id: 'napo',
    name: 'Napo',
    fullName: 'Filippo Napolitano',
    role: 'Ideatore · Dev · Dir. Amm.',
    emoji: '💡',
    hex: '#8b5cf6',
    threeColor: 0x8b5cf6,
    deskColor: 0xede9fe,
    screenColor: 0x7c3aed,
    position: [0, 0, -4],
    camPos: [0, 2.5, 0.5],
    camTarget: [0, 1.3, -4],
    bio: "La mente dietro tutto. Ogni lunedì ha l'idea del secolo. Il venerdì è già cambiata tre volte.",
    funFact: 'Il suo whiteboard ha un whiteboard figlio per i dettagli.',
    tags: ['Strategy', 'Vision', 'Admin', 'Dev'],
    deskType: 'director',
  },
  {
    id: 'andre',
    name: 'Andre',
    fullName: 'Andrea di Pietro',
    role: 'Tester · Supporto Tecnico',
    emoji: '🔍',
    hex: '#10b981',
    threeColor: 0x10b981,
    deskColor: 0xd1fae5,
    screenColor: 0x059669,
    position: [3, 0, 2],
    camPos: [3, 2.5, 6.5],
    camTarget: [3, 1.3, 2],
    bio: 'Il cacciatore di bug. Trova errori nel codice che non è ancora stato scritto.',
    funFact: 'Ha rotto 3 ambienti di staging solo guardandoli fissi.',
    tags: ['QA', 'Testing', 'Debug', 'Support'],
    deskType: 'tester',
  },
  {
    id: 'dalla',
    name: 'Dalla',
    fullName: 'Matteo Dallavalle',
    role: 'Developer · DB Admin · Support',
    emoji: '🗄️',
    hex: '#06b6d4',
    threeColor: 0x06b6d4,
    deskColor: 0xcffafe,
    screenColor: 0x0891b2,
    position: [8, 0, -3],
    camPos: [8, 2.5, 1.5],
    camTarget: [8, 1.3, -3],
    bio: 'Il custode dei dati. Sa dove vive ogni record, anche quelli che non sai di avere.',
    funFact: 'I suoi JOIN sono così ottimizzati che il database gli manda i complimenti.',
    tags: ['SQL', 'PostgreSQL', 'Dev', 'Support'],
    deskType: 'db',
  },
]
